### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by timlogemann** [elrumo/macOS_Big_Sur_icons_replacements#1097]
The results returned by the search functionality are terribly inaccurate. They seem to do some kind of fuzzy matching where they only return autocorrected matches and ignore direct matches for the search query. For example: searching 'Slack' only returns icons with the name 'Black' in them.

As you can see in this image, the first immediate results on the site contains a Spotify alternative icon:
<img width="410" alt="Screenshot 2021-02-15 at 10 51 32" src="https://user-images.githubusercontent.com/15154878/107930862-d9c29280-6f7b-11eb-8828-694f3f18ad75.png">

However, when searching for Spotify, none of the results are any of the actual direct Spotify replacements. Just a few related app icons:
<img width="425" alt="Screenshot 2021-02-15 at 10 51 23" src="https://user-images.githubusercontent.com/15154878/107930861-d8916580-6f7b-11eb-959e-a777dff444cf.png">

**Comment by elrumo** [comment]
Should be fixed now

**Comment by eproxus** [comment]
It's still broken.
<img width="1376" alt="Screen Shot 2021-03-16 at 17 19 30" src="https://user-images.githubusercontent.com/112878/111343524-cb9b8b00-867b-11eb-822f-47b4f638b38b.png">

**Comment by elrumo** [comment]
I've made a small change to the ranking logic and it should perform better now, can you confirm?

**Comment by eproxus** [comment]
@elrumo Looks much better, thanks! 🙏
